// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmiresiihmsvvhycazwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtaXJlc2lpaG1zdnZoeWNhend0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0MDQyNzAsImV4cCI6MjA3Njk4MDI3MH0.eoox2ImqbtO13G3A-zeuycVPvqvoV2iLrnb6nN0n07A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});